[connections.snowflake]
account = "ORBRNYB-JZ55551.snowflakecomputing.com"
user = "pratiyushverma6"
password = "Sanskari@23456"
role = "ACCOUNTADMIN"
warehouse = "SYSTEM$STREAMLIT_NOTEBOOK_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
